CREATE TABLE IF NOT EXISTS kids (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name TEXT NOT NULL,
    last_name TEXT,
    age INTEGER,
    birthday TEXT,
    allergies TEXT,
    notes TEXT
);

CREATE TABLE IF NOT EXISTS friends (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name TEXT NOT NULL,
    last_name TEXT,
    pfirst_name TEXT,
    plast_name TEXT,
    age INTEGER,
    birthday TEXT,
    allergies TEXT,
    notes TEXT
);

CREATE TABLE IF NOT EXISTS kids_friends (
    kid_id INTEGER REFERENCES kids(id) ON DELETE CASCADE ON UPDATE CASCADE,
    friend_id INTEGER REFERENCES friends(id) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY (kid_id, friend_id)
);

CREATE TABLE IF NOT EXISTS siblings (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    friend_id INTEGER REFERENCES friends(id) ON DELETE CASCADE ON UPDATE CASCADE
);


